### ISSUE TITLE
make PHP 8 compatible

### ISSUE THREAD

**Issue by cidious** [juanparati/laralog#4]
```
Error: Undefined constant "Elasticsearch\FILTER_FLAG_SCHEME_REQUIRED" in phar:///app/laralog.phar/Vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 2
```
Note that `FILTER_FLAG_SCHEME_REQUIRED` is deprecated since PHP 7.3 and removed in PHP 8.0.

Because the `FILTER_FLAG_HOST_REQUIRED` and `FILTER_FLAG_SCHEME_REQUIRED` constants are removed in PHP 8, attempting to use them will now throw a fatal error.

The easiest fix is to simply remove these two flags. filter_var() function when used with `FILTER_VALIDATE_URL` will always enforce the host-required and scheme-required conditions regardless of the presence of these two flags.

**Comment by cidious** [comment]
after fixing the sources there's another error:
```
Fatal error: Uncaught TypeError: fstat(): Argument #1 ($stream) must be of type resource, null given in phar:///app/laralog.phar/App/Model/Readers/Stream.php on line 2
```
PHP 8.0 release

**Comment by cidious** [comment]
as a workaround i've changed
`php laralog.phar elasticsearch --input=storage/logs/laravel.log --index=logstash`
into
`sh -c "tail -f storage/logs/laravel.log | php laralog.phar -v elasticsearch --index=logstash"`
and it works

**Comment by juanparati** [comment]
Thank you for report about the incompatibility issues.

😅 PHP 8 was released last week and I can see many early adopters started to use it.

It will work in a new branch that is adapted to PHP 8 during this week.

**Comment by juanparati** [comment]
Unfortunately some dependencies like "league/climate" and "elasticsearch/elasticsearch" doesn't support PHP 8 yet. 

I am afraid that I will have to wait until those dependencies are release and stable for PHP 8. 

I will keep this issue open in the meantime.

**Comment by juanparati** [comment]
I provided PHP 8 support long time ago.
