### ISSUE TITLE
Error Unable to send logs {"error":"no handler found for uri [/laraveltestindex/log] and method [POST]"}

### ISSUE THREAD

**Issue by devops-sts** [juanparati/laralog#5]
I am getting following error:
`Unable to send logs {"error":"no handler found for uri [/laraveltestindex/log] and method [POST]"}`

PHP version: 7.4
Elasticsearch host is reachable from the source machine.
Command I used in storage/logs directory:  `php -dmemory_limit=7g /usr/bin/laralog http://myelasticsearchhost:9200 --input=laravel.log --index=laraveltestindex`

**Comment by juanparati** [comment]
PHP 7.4 is not longer supported.

**Comment by devops-sts** [comment]
ok, sad news but its fine.
